layout_spectrum: 0.7885305
typography_spectrum: 0.2329749
color:
  saturation: 0.1463466
  lightness: 0.5819516
  brandStrength: 0.2093672
  rhythmicContrast: 0.9279643
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: slawomirurban
